name: 'AdoreMe Tech Static Checks Action'
description: 'Run static checks on a PHP project, annotate results and upload artifacts'
inputs:
  php-image:
    description: 'PHP image to use'
    required: true
  run-phpcs:
    description: 'Run PHPCS'
    required: true
    default: 'true'
  run-phpmd:
    description: 'Run PHPMD'
    required: true
    default: 'true'
  run-phpcpd:
    description: 'Run PHPCPD'
    required: true
    default: 'true'
  run-phpstan:
    description: 'Run PHPStan'
    required: true
    default: 'true'
  reports-path:
    description: 'Path to store reports'
    required: true
    default: 'build/reports'
runs:
  using: 'composite'
  steps:
    - name: 'Run PHP Checkstyle'
      if: ${{ inputs.run-phpcs == 'true' }}
      uses: adore-me/gha-php-checkstyle@v1.0.0
      with:
        php-image: ${{ inputs.php-image }}
        reports-path: ${{ inputs.reports-path }}

    - name: 'Run PHP MD'
      if: ${{ inputs.run-phpmd == 'true' }}
      uses: adore-me/gha-php-md@v1.0.0
      with:
        php-image: ${{ inputs.php-image }}
        reports-path: ${{ inputs.reports-path }}Î©

    - name: 'Run PHP CPD'
      if: ${{ inputs.run-phpcpd == 'true' }}
      uses: adore-me/gha-php-cpd@v1.0.0
      with:
        php-image: ${{ inputs.php-image }}
        reports-path: ${{ inputs.reports-path }}

    - name: 'Run PHP STAN'
      if: ${{ inputs.run-phpstan == 'true' }}
      uses: adore-me/gha-php-stan@v1.0.0
      with:
        php-image: ${{ inputs.php-image }}
        reports-path: ${{ inputs.reports-path }}

    - name: 'Save Static Checks artifacts'
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: static-checks-artifacts
        path: ${{ inputs.reports-path }}
