name: 'AdoreMe Tech Static Checks Action'
description: 'Run static checks on a PHP project, annotate results and upload artifacts'
inputs:
  php-image:
    description: 'PHP image to use'
    required: false
  run-phpcs:
    description: 'Run PHP Checkstyle'
    required: true
    default: 'true'
  phpcs-standard:
    description: 'PHP checkstyle standard to use, if run-phpcs is true'
    required: false
    default: 'PSR2'
  run-phpmd:
    description: 'Run PHP MD'
    required: true
    default: 'true'
  run-phpcpd:
    description: 'Run PHP CPD'
    required: true
    default: 'true'
  run-phpstan:
    description: 'Run PHP Stan'
    required: true
    default: 'true'
  reports-dir:
    description: 'Reports base directory'
    required: true
    default: 'build/reports'
  app-dir:
    description: 'Application directory - use without trailing slash. When empty will try to guess if is `src` or `app`.'
    required: false
    default: ''
  run-phprector:
    description: 'Run PHP Rector'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Set PHP image'
      id: set-php-image
      run: $GITHUB_ACTION_PATH/set-image.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}

    - name: 'Run PHP Checkstyle'
      if: ${{ inputs.run-phpcs == 'true' }}
      uses: adore-me/gha-php-checkstyle@v2.2.1
      with:
        php-image: ${{ steps.set-php-image.outputs.php-image }}
        report-dir: ${{ inputs.reports-dir }}
        phpcs-standard: ${{ inputs.phpcs-standard }}
        app-dir: ${{ inputs.app-dir }}

    - name: 'Run PHP MD'
      if: ${{ inputs.run-phpmd == 'true' }}
      uses: adore-me/gha-php-md@v2.1.1
      with:
        php-image: ${{ steps.set-php-image.outputs.php-image }}
        report-dir: ${{ inputs.reports-dir }}
        app-dir: ${{ inputs.app-dir }}

    - name: 'Run PHP CPD'
      if: ${{ inputs.run-phpcpd == 'true' }}
      uses: adore-me/gha-php-cpd@v2.1.0
      with:
        php-image: ${{ steps.set-php-image.outputs.php-image }}
        report-dir: ${{ inputs.reports-dir }}

    - name: 'Run PHP Stan'
      if: ${{ inputs.run-phpstan == 'true' }}
      uses: adore-me/gha-php-stan@v2.1.1
      with:
        php-image: ${{ steps.set-php-image.outputs.php-image }}
        report-dir: ${{ inputs.reports-dir }}
        app-dir: ${{ inputs.app-dir }}

    - name: 'Run PHP Rector'
      if: ${{ inputs.run-phprector == 'true' }}
      uses: adore-me/gha-php-rector@v1.0.1
      with:
        php-image: ${{ steps.set-php-image.outputs.php-image }}
        report-dir: ${{ inputs.reports-dir }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Save Static Checks artifacts'
      if: always()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: static-checks-artifacts
        path: ${{ inputs.reports-dir }}
